// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdW4K06_cazDYgN4f8tNjmLi2CTKZlvFs',
    appId: '1:376491685915:web:496c6e42e07a1be813e0be',
    messagingSenderId: '376491685915',
    projectId: 'safeguard-parental-control',
    authDomain: 'safeguard-parental-control.firebaseapp.com',
    storageBucket: 'safeguard-parental-control.firebasestorage.app',
    measurementId: 'G-KPJXNQ3HEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb0h9K6GWsmWZGFKHpUHs92HcaouX8TDs',
    appId: '1:376491685915:android:7edfec120245fc6513e0be',
    messagingSenderId: '376491685915',
    projectId: 'safeguard-parental-control',
    storageBucket: 'safeguard-parental-control.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEhDVKKhRkFBu44w5DgPfs4uHY1RPp3YY',
    appId: '1:376491685915:ios:46c3dd039b53f3ed13e0be',
    messagingSenderId: '376491685915',
    projectId: 'safeguard-parental-control',
    storageBucket: 'safeguard-parental-control.firebasestorage.app',
    iosBundleId: 'com.example.safeguardParentalControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEhDVKKhRkFBu44w5DgPfs4uHY1RPp3YY',
    appId: '1:376491685915:ios:46c3dd039b53f3ed13e0be',
    messagingSenderId: '376491685915',
    projectId: 'safeguard-parental-control',
    storageBucket: 'safeguard-parental-control.firebasestorage.app',
    iosBundleId: 'com.example.safeguardParentalControl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdW4K06_cazDYgN4f8tNjmLi2CTKZlvFs',
    appId: '1:376491685915:web:e2e3dcf1a15d71b213e0be',
    messagingSenderId: '376491685915',
    projectId: 'safeguard-parental-control',
    authDomain: 'safeguard-parental-control.firebaseapp.com',
    storageBucket: 'safeguard-parental-control.firebasestorage.app',
    measurementId: 'G-R3PPGJXRLN',
  );
}
